services:
  - type: web
    name: connecthub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT yourproject.asgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: REDIS_URL
        value: redis://...  # from Upstash or Redis provider
